# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pokename 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "pokename"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Lucas Saldanha"]
  s.date = "2015-06-21"
  s.description = "This gem choose one from the 151 Pok\u{e9}mons names (Yeah, just the first generation) to be used in your projects."
  s.email = "lucascrsaldanha@gmail"
  s.executables = ["pokename"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/pokename",
    "lib/pokename.rb",
    "pokename.gemspec",
    "test/helper.rb",
    "test/test_pokename.rb"
  ]
  s.homepage = "http://github.com/lucascrsaldanha/pokename"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Choose a random Pok\u{e9}mon name to name your project"
end

